### PR TITLE
enum, export, part, part of, library, and mixin tags

### PR DESCRIPTION
**Pull request by jrc2139**
also removed parsing the getters params because they have none.

will put up a PR with tagbar to make use of them!

> Screenshot 2020-08-05 at 21 49 58

> Screenshot 2020-08-05 at 21 50 54

### CODE REVIEW

**Comment by jrc2139** [comment]
Screenshot 2020-08-05 at 21 50 54
Screenshot 2020-08-05 at 21 49 58

**Comment by alerque** [comment]
Hey, VIM `tagbar` maintainer here, just dropping by to see if this has been merged yet. I'll be happy to merge the PR that includes support for this as soon as it hits upstream here.

**Comment by jrc2139** [comment]
Screen Shot 2020-08-26 at 22 06 27

**Comment by jrc2139** [comment]
Screen Shot 2020-08-26 at 22 08 14

**Comment by nerdrew** [comment]
Sorry for the absurdly long delay (again)! Is this good to merge?

**Comment by jrc2139** [comment]
> Sorry for the absurdly long delay (again)! Is this good to merge?

yes i've been using this for months now without issues.

**Comment by jrc2139** [comment]
also, i created an additional sort of the import directives.  you specify your project's name as a flag in the dart_ctags command:

Screen Shot 2020-11-25 at 19 01 31

**Comment by nerdrew** [comment]
Published this version.

**Comment by jrc2139** [comment]
k ill let the tagbar maintainers know!

**Pull request merged**
